services:
    millwright_rad.form.entity_to_id.transformer:
        class: FOS\UserBundle\Form\DataTransformer\UserToUsernameTransformer
        arguments:
            - @doctrine.orm.entity_manager

    millwright_rad.form.group_to_id_transformer:
        class: Millwright\RadBundle\Form\DataTransformer\EntityToIdTransformer
        arguments:
            - @doctrine.orm.entity_manager

    millwright_rad.form.group_select_type:
        class: Millwright\RadBundle\Form\Type\EntitySelectFormType
        arguments:
            - @millwright_rad.form.group_to_id_transformer
        tags:
            - { name: form.type, alias: 'entity_selector' }

    millwright_rad.form.days_to_seconds_transformer:
        class: Millwright\RadBundle\Form\DataTransformer\SecondsToDaysTransformer
        public: false

    millwright_rad.form.days.type:
        class: Millwright\RadBundle\Form\Type\DaysFormType
        arguments:
            - @millwright_rad.form.days_to_seconds_transformer
        tags:
            - { name: form.type, alias: days }
