services:
    millwright_rad.form.group_select_type:
        class: Millwright\RadBundle\Form\Type\EntitySelectFormType
        tags:
            - { name: form.type, alias: 'entity_selector' }

    millwright_rad.form.days_to_seconds_transformer:
        class: Millwright\RadBundle\Form\DataTransformer\SecondsToDaysTransformer
        public: false

    millwright_rad.form.days.type:
        class: Millwright\RadBundle\Form\Type\DaysFormType
        arguments:
            - @millwright_rad.form.days_to_seconds_transformer
        tags:
            - { name: form.type, alias: days }
