services:
    millwright_rad.form.group_select_type:
        class: Millwright\RadBundle\Form\Type\EntitySelectFormType
        tags:
            - { name: form.type, alias: 'entity_choice' }

    millwright_rad.form.days_to_seconds_transformer:
        class: Millwright\RadBundle\Form\DataTransformer\SecondsToDaysTransformer
        public: false

    millwright_rad.form.days.type:
        class: Millwright\RadBundle\Form\Type\DaysFormType
        arguments:
            - @millwright_rad.form.days_to_seconds_transformer
        tags:
            - { name: form.type, alias: days }

    millwright_rad.phone_form_type:
        class: Millwright\RadBundle\Form\Type\PhoneFormType
        arguments:
            - @millwright_rad.phone.transformer
        tags:
            - { name: form.type, alias: 'phone'}

    millwright_rad.phone.transformer:
        class: Millwright\RadBundle\Form\DataTransformer\PhoneToPhoneViewTransformer
        public: false

    millwright_rad.form.date_picker:
            class: Millwright\RadBundle\Form\Type\DatePickerFormType
            arguments:
                - %millwright_rad.date_format%
            tags:
                - { name: form.type, alias: 'date_picker' }


    millwright_rad.form.date_time_picker:
            class: Millwright\RadBundle\Form\Type\DateTimePickerFormType
            arguments:
                - %millwright_rad.date_time_format%
            tags:
                - { name: form.type, alias: 'date_time_picker' }
