services:
    millwright_rad.form.group_select_type:
        class: Millwright\RadBundle\Form\Type\EntitySelectFormType
        tags:
            - { name: form.type, alias: 'entity_choice' }

    millwright_rad.form.days_to_seconds_transformer:
        class: Millwright\RadBundle\Form\DataTransformer\SecondsToDaysTransformer
        public: false

    millwright_rad.form.days.type:
        class: Millwright\RadBundle\Form\Type\DaysFormType
        arguments:
            - @millwright_rad.form.days_to_seconds_transformer
        tags:
            - { name: form.type, alias: days }

    millwright_rad.phone_form_type:
        class: Millwright\RadBundle\Form\Type\PhoneFormType
        arguments:
            - @millwright_rad.phone.transformer
        tags:
            - { name: form.type, alias: 'phone'}

    millwright_rad.phone.transformer:
        class: Millwright\RadBundle\Form\DataTransformer\PhoneToPhoneViewTransformer
        public: false