parameters:
    millwright_rad.status_mapper.class: Millwright\RadBundle\Twig\StatusMapper
    millwright_rad.status_mapper.class: Millwright\RadBundle\Twig\StatusMapper
    security.acl.object_identity_retrieval_strategy.class: Millwright\RadBundle\Security\Acl\Domain\ORM\ORMObjectIdentityRetrievalStrategy

services:
    millwright_rad.entity_to_id_transformer:
        class: FOS\UserBundle\Form\DataTransformer\UserToUsernameTransformer
        arguments:
            - @doctrine.orm.entity_manager

    security.acl.object_identity_retrieval_strategy:
        class: %security.acl.object_identity_retrieval_strategy.class%
        arguments:
            - @doctrine.orm.entity_manager
