parameters:
    millwright_rad.status_mapper.class: Millwright\RadBundle\Twig\StatusMapper
    millwright_rad.status_mapper.class: Millwright\RadBundle\Twig\StatusMapper
    security.acl.object_identity_retrieval_strategy.class: Millwright\RadBundle\Security\Acl\Domain\ORM\ORMObjectIdentityRetrievalStrategy

services:
    millwright_rad.entity_to_id_transformer:
        class: FOS\UserBundle\Form\DataTransformer\UserToUsernameTransformer
        arguments:
            - @doctrine.orm.entity_manager

    security.acl.object_identity_retrieval_strategy:
        class: %security.acl.object_identity_retrieval_strategy.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @validator.mapping.class_metadata_factory

    millwright_rad.form.group_to_id_transformer:
        class: Millwright\RadBundle\Form\DataTransformer\EntityToIdTransformer
        arguments:
            - @doctrine.orm.entity_manager

    millwright_rad.form.group_select_type:
        class: Millwright\RadBundle\Form\Type\EntitySelectFormType
        arguments:
            - @millwright_rad.form.group_to_id_transformer
        tags:
            - { name: form.type, alias: entity_selector }