parameters:
    millwright_rad.status_mapper.class: Millwright\RadBundle\Twig\StatusMapper
    millwright_rad.date_format: 'dd.mm.yyyy'
    millwright_rad.date_time_format: 'dd.mm.yyyy hh:mm:ss'

services:
    millwright_rad.twig.extension:
        class: Millwright\RadBundle\Twig\RadExtension
        arguments:
            - %millwright_rad.date_format%
        tags:
            - { name: twig.extension }
