services:
    millwright_rad.validator.date_not_less_than_current:
        class: Boombate\ContractOwnershipBundle\Validator\DateNotLessThanCurrentValidator
        tags:
            - { name: 'validator.constraint_validator', alias: 'millwright_rad.validator.date_not_less_than_current' }

    millwright_rad.validator.phone:
        class: Boombate\ContractOwnershipBundle\Validator\Phone
        tags:
            - { name: 'validator.constraint_validator', alias: 'millwright_rad.validator.phone'}
